/**
 * Rich sample dataset for demo / offline mode — loaded when Firebase is not configured
 * or EXPO_PUBLIC_DEMO_MODE keeps the app on local demo data (see env.ts).
 */
import type {
  ActivityItem,
  AIInsight,
  Material,
  Notification,
  Project,
  Task,
  UserProfile,
} from '../types';

/** Demo clock anchor — keeps deadlines & activity timestamps coherent with “today”. */
const DEMO_NOW = new Date('2026-05-20T14:30:00Z');

export const DEMO_USER: UserProfile = {
  id: 'demo-user-1',
  email: 'admin@buildtrack.demo',
  displayName: 'Alex Rivera',
  role: 'builder',
  company: 'Rivera Construction Co.',
  phone: '+1 (555) 012-3456',
  createdAt: '2026-01-08T12:00:00Z',
};

export const DEMO_PROJECTS: Project[] = [
  {
    id: 'proj-1',
    name: 'Skyline Tower Phase 2',
    location: 'Downtown Metro — Block C, Site 12',
    description:
      '32-story mixed-use tower: structural cores complete through L24; curtain wall and MEP fit-out through L18.',
    status: 'active',
    progress: 71,
    startDate: '2026-01-15',
    endDate: '2027-03-31',
    supervisorName: 'Maria Chen',
    createdAt: '2026-01-10T09:00:00Z',
    updatedAt: DEMO_NOW.toISOString(),
  },
  {
    id: 'proj-2',
    name: 'Harbor Bridge Retrofit',
    location: 'East Waterfront — Span B/C Approach',
    description:
      'Steel retrofit, bearing replacements, deck hydro-demolition, and UHPC overlay on critical spans.',
    status: 'active',
    progress: 46,
    startDate: '2026-02-03',
    endDate: '2026-11-15',
    supervisorName: 'James Okonkwo',
    createdAt: '2026-01-28T14:20:00Z',
    updatedAt: DEMO_NOW.toISOString(),
  },
  {
    id: 'proj-3',
    name: 'Greenfield Residential — Birch Row',
    location: 'North Ridge Estates — Lots 7–9',
    description:
      '48 townhomes: foundations wrapped; framing crews mobilizing block B; utilities trenching underway.',
    status: 'active',
    progress: 34,
    startDate: '2026-03-10',
    endDate: '2027-08-01',
    supervisorName: 'Sofia Patel',
    createdAt: '2026-03-01T11:00:00Z',
    updatedAt: DEMO_NOW.toISOString(),
  },
  {
    id: 'proj-4',
    name: 'Meridian Cold Chain Annex',
    location: 'Industrial Park Route 9 — Pad D',
    description:
      '110k sq ft refrigerated annex — insulated panels on hold pending envelope engineer sign-off.',
    status: 'on_hold',
    progress: 58,
    startDate: '2026-02-18',
    supervisorName: 'Daniel Rhodes',
    createdAt: '2026-02-12T08:45:00Z',
    updatedAt: DEMO_NOW.toISOString(),
  },
];

export const DEMO_MATERIALS: Material[] = [
  {
    id: 'mat-1',
    name: 'Portland Cement Type I/II',
    category: 'cement',
    quantity: 580,
    unit: 'bags',
    minThreshold: 240,
    projectId: 'proj-1',
    supplier: 'Summit Ready-Mix Supply',
    lastUpdated: DEMO_NOW.toISOString(),
    usageHistory: [
      { id: 'u1', amount: 52, date: '2026-05-18', note: 'L22 slab strip pour' },
      { id: 'u2', amount: 68, date: '2026-05-15', note: 'Core walls L21–22' },
      { id: 'u3', amount: 44, date: '2026-05-11', note: 'Pump staging bay mud slab' },
    ],
  },
  {
    id: 'mat-2',
    name: 'Rebar #6 Grade 60 (stock lengths)',
    category: 'steel',
    quantity: 72,
    unit: 'tons',
    minThreshold: 95,
    projectId: 'proj-1',
    supplier: 'Columbia Reinforcing',
    lastUpdated: DEMO_NOW.toISOString(),
  },
  {
    id: 'mat-3',
    name: 'CMU — 8″ Normal Weight',
    category: 'bricks',
    quantity: 9200,
    unit: 'units',
    minThreshold: 4500,
    projectId: 'proj-3',
    supplier: 'Harbor Masonry',
    lastUpdated: DEMO_NOW.toISOString(),
  },
  {
    id: 'mat-4',
    name: 'Structural Fill Sand — Certified',
    category: 'sand',
    quantity: 38,
    unit: 'cu yd',
    minThreshold: 85,
    projectId: 'proj-3',
    supplier: 'North Ridge Aggregates',
    lastUpdated: DEMO_NOW.toISOString(),
  },
  {
    id: 'mat-5',
    name: 'Industrial Epoxy Deck Coating',
    category: 'paint',
    quantity: 142,
    unit: 'gal',
    minThreshold: 120,
    projectId: 'proj-2',
    supplier: 'ProtectCoat Marine',
    lastUpdated: DEMO_NOW.toISOString(),
  },
  {
    id: 'mat-6',
    name: 'THHN Copper 12 AWG (reel)',
    category: 'electrical',
    quantity: 2100,
    unit: 'ft',
    minThreshold: 3200,
    projectId: 'proj-1',
    supplier: 'ElectroMax Wholesale',
    lastUpdated: DEMO_NOW.toISOString(),
  },
  {
    id: 'mat-7',
    name: 'Shear Studs 3/4″ x 5″',
    category: 'steel',
    quantity: 620,
    unit: 'pcs',
    minThreshold: 800,
    projectId: 'proj-2',
    supplier: 'Great Lakes Steel Fab',
    lastUpdated: DEMO_NOW.toISOString(),
  },
  {
    id: 'mat-8',
    name: 'Exterior Acrylic Primer — White',
    category: 'paint',
    quantity: 36,
    unit: 'gal',
    minThreshold: 60,
    projectId: 'proj-3',
    supplier: 'PaintPro Jobsite Direct',
    lastUpdated: DEMO_NOW.toISOString(),
  },
  {
    id: 'mat-9',
    name: 'PVC Electrical Conduit 2″ SCH 40',
    category: 'electrical',
    quantity: 118,
    unit: 'ft',
    minThreshold: 200,
    projectId: 'proj-3',
    supplier: 'ElectroMax Wholesale',
    lastUpdated: DEMO_NOW.toISOString(),
  },
  {
    id: 'mat-10',
    name: 'Type S Mortar Mix',
    category: 'cement',
    quantity: 96,
    unit: 'bags',
    minThreshold: 140,
    projectId: 'proj-3',
    supplier: 'Summit Ready-Mix Supply',
    lastUpdated: DEMO_NOW.toISOString(),
  },
  {
    id: 'mat-11',
    name: 'PIR Insulated Metal Panel — Freezer Grade',
    category: 'steel',
    quantity: 840,
    unit: 'sq ft',
    minThreshold: 1200,
    projectId: 'proj-4',
    supplier: 'Polar Panel Systems',
    lastUpdated: DEMO_NOW.toISOString(),
  },
  {
    id: 'mat-12',
    name: 'Galvanized Sheet — 18 ga',
    category: 'steel',
    quantity: 44,
    unit: 'sheets',
    minThreshold: 75,
    projectId: 'proj-4',
    supplier: 'Great Lakes Steel Fab',
    lastUpdated: DEMO_NOW.toISOString(),
  },
];

export const DEMO_TASKS: Task[] = [
  {
    id: 'task-1',
    title: 'Pour & cure — Level 22 slab (Zone B)',
    description:
      'Coordinate 38 m boom pump, vapor barrier QC, and hydration blankets per structural memo Rev F.',
    status: 'in_progress',
    assignedTo: 'user-super-1',
    assignedToName: 'Maria Chen',
    projectId: 'proj-1',
    projectName: 'Skyline Tower Phase 2',
    deadline: '2026-05-28',
    progress: 62,
    createdAt: '2026-05-08T09:00:00Z',
    updatedAt: DEMO_NOW.toISOString(),
  },
  {
    id: 'task-2',
    title: 'Steel delivery QA — Span B tendon ducts',
    description:
      'Witness ultrasonic bolt tension samples; reject non-conforming galvanized brackets lot #4421.',
    status: 'pending',
    assignedTo: 'user-super-2',
    assignedToName: 'James Okonkwo',
    projectId: 'proj-2',
    projectName: 'Harbor Bridge Retrofit',
    deadline: '2026-05-14',
    progress: 0,
    createdAt: '2026-05-06T13:30:00Z',
    updatedAt: DEMO_NOW.toISOString(),
  },
  {
    id: 'task-3',
    title: 'Electrical rough-in — Levels 14–15 east riser',
    description:
      'Complete conduit homeruns per EE-312; coordinate ceiling inspections Tuesday AM.',
    status: 'in_progress',
    assignedTo: 'user-super-1',
    assignedToName: 'Maria Chen',
    projectId: 'proj-1',
    projectName: 'Skyline Tower Phase 2',
    deadline: '2026-06-02',
    progress: 48,
    createdAt: '2026-05-02T16:00:00Z',
    updatedAt: DEMO_NOW.toISOString(),
  },
  {
    id: 'task-4',
    title: 'Formal site safety audit — Q2',
    description: 'OSHA walkthrough including swing-stage harness audit on bridge spans.',
    status: 'completed',
    assignedTo: 'user-super-2',
    assignedToName: 'James Okonkwo',
    projectId: 'proj-2',
    projectName: 'Harbor Bridge Retrofit',
    deadline: '2026-05-12',
    progress: 100,
    createdAt: '2026-05-01T10:00:00Z',
    updatedAt: DEMO_NOW.toISOString(),
  },
  {
    id: 'task-5',
    title: 'Survey stakes — Birch Row utilities corridor',
    description:
      'Verify invert elevations against civil sheets C-402 series before trench inspections.',
    status: 'pending',
    assignedTo: 'user-super-3',
    assignedToName: 'Sofia Patel',
    projectId: 'proj-3',
    projectName: 'Greenfield Residential — Birch Row',
    deadline: '2026-05-08',
    progress: 0,
    createdAt: '2026-04-26T08:30:00Z',
    updatedAt: DEMO_NOW.toISOString(),
  },
  {
    id: 'task-6',
    title: 'Waterproofing — podium planters & drains',
    description:
      'Install Henry Blueskin transitions per detail 8/A7. Hold point for envelope consultant.',
    status: 'in_progress',
    assignedTo: 'user-super-1',
    assignedToName: 'Maria Chen',
    projectId: 'proj-1',
    projectName: 'Skyline Tower Phase 2',
    deadline: '2026-05-17',
    progress: 55,
    createdAt: '2026-05-09T14:15:00Z',
    updatedAt: DEMO_NOW.toISOString(),
  },
  {
    id: 'task-7',
    title: 'Chilled water piping leak test — annex',
    description:
      'Nitrogen holding test per MECH spec §22 63 00; log gauges every 30 minutes.',
    status: 'pending',
    assignedTo: 'user-super-4',
    assignedToName: 'Daniel Rhodes',
    projectId: 'proj-4',
    projectName: 'Meridian Cold Chain Annex',
    deadline: '2026-06-10',
    progress: 0,
    createdAt: '2026-05-11T09:45:00Z',
    updatedAt: DEMO_NOW.toISOString(),
  },
  {
    id: 'task-8',
    title: 'Deck overlay cure monitoring — Lane 2 closure',
    description:
      'Maintain moisture blankets 72 hr min; coordinate MOT lane shifts with city DOT liaison.',
    status: 'in_progress',
    assignedTo: 'user-super-2',
    assignedToName: 'James Okonkwo',
    projectId: 'proj-2',
    projectName: 'Harbor Bridge Retrofit',
    deadline: '2026-05-23',
    progress: 35,
    createdAt: '2026-05-13T07:00:00Z',
    updatedAt: DEMO_NOW.toISOString(),
  },
  {
    id: 'task-9',
    title: 'Precast stair flights — crane picks Lot 8',
    description:
      'Lift plan filed; rigging inspector on site 06:30; exclusion zone signage verified.',
    status: 'completed',
    assignedTo: 'user-super-3',
    assignedToName: 'Sofia Patel',
    projectId: 'proj-3',
    projectName: 'Greenfield Residential — Birch Row',
    deadline: '2026-05-18',
    progress: 100,
    createdAt: '2026-05-10T11:20:00Z',
    updatedAt: DEMO_NOW.toISOString(),
  },
  {
    id: 'task-10',
    title: 'Compaction proof-roll — Phase 2 pad footings',
    description:
      'Geotech observation letter due before forming permit closes Friday COB.',
    status: 'in_progress',
    assignedTo: 'user-super-3',
    assignedToName: 'Sofia Patel',
    projectId: 'proj-3',
    projectName: 'Greenfield Residential — Birch Row',
    deadline: '2026-05-27',
    progress: 70,
    createdAt: '2026-05-14T08:10:00Z',
    updatedAt: DEMO_NOW.toISOString(),
  },
];

export const DEMO_NOTIFICATIONS: Notification[] = [
  {
    id: 'notif-1',
    title: 'Low stock — Structural steel',
    message:
      'Rebar #6 inventory at Skyline Tower is 72 tons vs 95 ton threshold. Expedite Columbia Reinforcing PO #88421.',
    type: 'low_stock',
    read: false,
    createdAt: new Date(DEMO_NOW.getTime() - 45 * 60 * 1000).toISOString(),
    projectId: 'proj-1',
  },
  {
    id: 'notif-2',
    title: 'Low stock — Electrical rough-in',
    message:
      'THHN 12 AWG footage below warehouse reorder point (2100 ft remaining vs 3200 ft minimum).',
    type: 'low_stock',
    read: false,
    createdAt: new Date(DEMO_NOW.getTime() - 3 * 60 * 60 * 1000).toISOString(),
    projectId: 'proj-1',
  },
  {
    id: 'notif-3',
    title: 'Deadline overdue — QA inspection',
    message:
      'Steel delivery QA for Harbor Bridge Span B tendon ducts was due May 14 — escalate to subcontractor.',
    type: 'deadline',
    read: false,
    createdAt: new Date(DEMO_NOW.getTime() - 2 * 60 * 60 * 1000).toISOString(),
    projectId: 'proj-2',
  },
  {
    id: 'notif-4',
    title: 'AI schedule risk',
    message:
      'Model estimates 4.5 day slip on L22 pour if sand and shear stud orders are not confirmed by May 21.',
    type: 'ai_warning',
    read: false,
    createdAt: new Date(DEMO_NOW.getTime() - 20 * 60 * 60 * 1000).toISOString(),
    projectId: 'proj-1',
  },
  {
    id: 'notif-5',
    title: 'Project milestone',
    message: 'Harbor Bridge retrofit progress updated to 46% after overlay crew productivity gain.',
    type: 'project_update',
    read: true,
    createdAt: new Date(DEMO_NOW.getTime() - 26 * 60 * 60 * 1000).toISOString(),
    projectId: 'proj-2',
  },
  {
    id: 'notif-6',
    title: 'Low stock — Birch Row civil',
    message: 'Certified structural fill sand is 38 cu yd vs 85 cu yd minimum before backfill resumes.',
    type: 'low_stock',
    read: true,
    createdAt: new Date(DEMO_NOW.getTime() - 50 * 60 * 60 * 1000).toISOString(),
    projectId: 'proj-3',
  },
];

export const DEMO_ACTIVITIES: ActivityItem[] = [
  {
    id: 'act-1',
    type: 'material',
    message: '52 bags Type I/II cement issued — Skyline L22 pour (Zone B)',
    timestamp: new Date(DEMO_NOW.getTime() - 50 * 60 * 1000).toISOString(),
    projectId: 'proj-1',
  },
  {
    id: 'act-2',
    type: 'task',
    message: 'Task completed: Precast stair flights — crane picks Lot 8',
    timestamp: new Date(DEMO_NOW.getTime() - 3 * 60 * 60 * 1000).toISOString(),
    projectId: 'proj-3',
  },
  {
    id: 'act-3',
    type: 'project',
    message: 'Meridian annex hold: envelope engineer RFI #12 — panel fastener spacing',
    timestamp: new Date(DEMO_NOW.getTime() - 5 * 60 * 60 * 1000).toISOString(),
    projectId: 'proj-4',
  },
  {
    id: 'act-4',
    type: 'material',
    message: 'Delivered 120 PIR panel sheets — Meridian dock 3 (partial release)',
    timestamp: new Date(DEMO_NOW.getTime() - 8 * 60 * 60 * 1000).toISOString(),
    projectId: 'proj-4',
  },
  {
    id: 'act-5',
    type: 'task',
    message: 'Task completed: Formal site safety audit — Q2 (bridge & tower sites)',
    timestamp: new Date(DEMO_NOW.getTime() - 18 * 60 * 60 * 1000).toISOString(),
    projectId: 'proj-2',
  },
  {
    id: 'act-6',
    type: 'ai',
    message: 'BuildTrack AI refreshed cross-site procurement risk summary',
    timestamp: new Date(DEMO_NOW.getTime() - 22 * 60 * 60 * 1000).toISOString(),
  },
];

export const DEMO_INSIGHTS: AIInsight[] = [
  {
    id: 'insight-1',
    title: 'Cross-site material conflict (next 72h)',
    summary:
      'Skyline Tower and Harbor Bridge both pull from the same shear stud and galvanized sheet pool. Consolidate to one overnight drop to avoid duplicate flatbed fees and QC hold times.',
    priority: 'high',
    createdAt: DEMO_NOW.toISOString(),
  },
  {
    id: 'insight-2',
    title: 'Birch Row critical path exposure',
    summary:
      'Survey utilities + compaction report gates concrete footings pour. Sequencing slip of 2 days cascades framing start on Block B — consider split shift for survey closure.',
    priority: 'high',
    createdAt: DEMO_NOW.toISOString(),
  },
  {
    id: 'insight-3',
    title: 'MER cold annex — restart readiness',
    summary:
      'When envelope RFI clears, insulated panel crews need 11 days notice. Pre-stage crane matting this week to shave 1.5 days off remobilization.',
    priority: 'medium',
    createdAt: DEMO_NOW.toISOString(),
  },
  {
    id: 'insight-4',
    title: 'Productivity lift on bridge overlay',
    summary:
      'Night crew throughput on Deck Lane 2 is 18% above plan after LED light tower upgrade — model suggests finishing overlay 3 shifts early if weather holds.',
    priority: 'low',
    createdAt: DEMO_NOW.toISOString(),
  },
];

/** Demo login credentials */
export const DEMO_CREDENTIALS = {
  email: 'admin@buildtrack.demo',
  password: 'demo1234',
  supervisorEmail: 'supervisor@buildtrack.demo',
  supervisorPassword: 'demo1234',
};
